name: Pull requests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build for JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'corretto'
      - name: Build with Gradle
        run: ./gradlew build
  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    needs: build
    env:
      IS_PULL_REQUEST: "true"
      HAVE_NEEDED_DATA: ${{ secrets.gpr_user != '' && secrets.gpr_token != '' }}
    steps:
      - name: Validate publish secrets
        if: ${{ env.HAVE_NEEDED_DATA != 'true' }}
        run: |
          echo "The secrets for publish are not set."
          exit 0
      - uses: actions/checkout@v4
        if: ${{ env.HAVE_NEEDED_DATA == 'true' }}
      - uses: actions/cache@v4
        if: ${{ env.HAVE_NEEDED_DATA == 'true' }}
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v4
        if: ${{ env.HAVE_NEEDED_DATA == 'true' }}
        with:
          java-version: 11
          distribution: 'corretto'
      - name: Publish with Gradle
        if: ${{ env.HAVE_NEEDED_DATA == 'true' }}
        run: ./gradlew -x test publishAllPublicationsToGitHubPackagesRepository
        env:
          GRP_USER: ${{ secrets.gpr_user }}
          GRP_TOKEN: ${{ secrets.gpr_token }}
